### ISSUE TITLE
[Feature Suggestion] Ability to track a resource in the selection window.

### ISSUE THREAD

**Issue by wonderfulnewworld** [Gerark/just-popcorn-initiative#5]
Trying to experiment with a modified version of popcorn initiative, using a custom system that has a Speed stat, and I want to show characters' Speed in the selection window to put a (honor system, manual) restriction on which character can be selected to go next. (Ie, you can only pick someone with = or+/- 1 Speed variation from yours.) My idea would to just have it be next to the player color, so it could be something you look at quickly rather than having to open another window. [Even more ideally would be to put a check to prevent characters who don't fall in this threshold from showing up in the selection window at all, but as I understand this module's supposed to be very lightweight, so I don't want to push it by asking too much.]
![image](https://github.com/Gerark/just-popcorn-initiative/assets/99152399/848cdacd-000c-4fc6-bc67-6da2eba66961)

**Comment by Gerark** [comment]
I initially considered allowing the choice of stats to add to each Actor in the module ( but opted to exclude it from the first version ) so your suggestion confirms that this was likely a good decision.

However, I have reservations about filtering the selection to display only certain actors. This aspect could introduce complexity, especially if the filtering dynamically changes based on the battle's state.

Would it be acceptable if you could view the total "Speed" value and perform the calculation yourself, with the ability to sort the selectable actors by their Speed?

**Comment by wonderfulnewworld** [comment]
Yeah, stat display with sorting would be great, more than enough info to perform the calculation. Adding more ease of use, you could also display the previous actors' stat in the side bar, so they don't have to quickly turn to their character sheet to remember their own stat too.

![image](https://github.com/Gerark/just-popcorn-initiative/assets/99152399/41adb5dd-d2de-4067-b11d-a6744e634b5a)

**Comment by Gerark** [comment]
Sounds good! I'm currently working on a different module, but I can probably start working on this in a few weeks.

Here are the key points:

- Provide the option to display any stats linked to an actor, making it easily configurable.
- Allow each stat to be configured for showing or hiding from players.
- Consider adding a way to display one or multiple stats alongside the character card (layout design details to be decided later).
- Enable sorting of characters by one or multiple stats.
- Include configuration options for default actor sorting when opening the Selection Window and potentially prioritizing player characters.
 
As for stretch goals:
- Consider implementing custom operations on stats, such as showing the difference between the selectable characters' speed and the last character. This could involve using macros attached to the stats, acting as modifiers.

Lot of stuff but I like the idea even if it might take a while.

**Comment by Gerark** [comment]
Here's a potential layout proposal. It's still a long way to the implementation of the feature tho.

I'm taking the time to redesign a bit the layout and adding little qol things.

https://github.com/Gerark/just-popcorn-initiative/assets/7666672/7053a921-7dd6-4796-a61d-e74d7ac28b5c

**Comment by wonderfulnewworld** [comment]
Ooooh, very nice!

**Comment by Gerark** [comment]
Hi, I released a new version of this extension with a new layout and support to stats visualization.
I decided not to go with too much complexity so the stats are there just to be visualized so I left out the constraints/sort proposal for now.

I'm going to focus on other extensions for the time being but let me know what you think about it.

Here's the part of the documentation which is talking about that aspect: https://github.com/Gerark/just-popcorn-initiative/tree/main#stats

**Comment by figomez** [comment]
Finally had a time to check it out, it's great, a big help! And the new ui is so good looking too!

**Comment by figomez** [comment]
Actually, I found a bug. So, I use token wildcard to cut down on having to make a lot of enemy actors, they all share one common actor, then I give them different images, and update their stats, but don't link them to actor, it's just saved per token. As a result, the stat doesn't line up with my tokens, since it appears popcorn uses the actor data instead.
![image](https://github.com/Gerark/just-popcorn-initiative/assets/81261388/73ec4be3-601c-4fb4-9cf3-04129fda6cec)

**Comment by Gerark** [comment]
Oh I see. Yes that's how it works at the moment. I'm not getting the info from the token instance but the actor. Do you think this should be an option or it should always get info from the token instead?

**Comment by wonderfulnewworld** [comment]
I think it should be an option, a lot of modules have it as an option.
